Map<int, String> migrationScriptsViePrgr = {
  1: '''
      CREATE TABLE vie_prgr(
        codgrad INTEGER,
        codprod INTEGER,
        livreid TEXT,
        refgrad TEXT,
        ideprod TEXT,
        estiest REAL,
        desprod TEXT,
        cl4prod INTEGER,
        cl1prod INTEGER,
        cl2prod INTEGER,
        nomprod TEXT,
        espprod TEXT,
        metgrad REAL,
        maxacre REAL,
        desmaxi REAL,
        unvgrad INTEGER,
        parfide INTEGER,
        agrgrad INTEGER,
        nomdivi TEXT,
        nomsubd TEXT,
        lismate INTEGER,
        desprom REAL,
        escombo INTEGER,
        negprod INTEGER,
        estsald REAL,
        prodtin TEXT,
        prodtfi TEXT,
        preprom REAL,
        preatac REAL,
        regr_sa INTEGER,
        ipiregr INTEGER,
        p_cregr INTEGER,
        fdenicm INTEGER,
        pdenicm INTEGER,
        nfcicms INTEGER,
        fforicm INTEGER,
        jdenicm INTEGER,
        jforicm INTEGER,
        pforicm INTEGER,
        ipi_ent INTEGER,
        p_c_ent INTEGER,
        icmdent INTEGER,
        icmfent INTEGER,
        ajuprec INTEGER,
        desunid TEXT,
        composicao TEXT,
        imgUrl TEXT,
        prevend REAL,
        fatconv REAL,
        lo1grad TEXT,
        lo2grad TEXT,
        lo3grad TEXT,
        filesto TEXT
      )
      ''',
  2: 'ALTER TABLE vie_prgr ADD COLUMN imagens TEXT;',
  3: 'ALTER TABLE vie_prgr ADD COLUMN qtdatac REAL;',
  4: 'ALTER TABLE vie_prgr ADD COLUMN preuffe REAL;',
  5: 'ALTER TABLE vie_prgr ADD COLUMN proplan INTEGER;',
  6: 'ALTER TABLE vie_prgr ADD COLUMN datvenc TEXT;',
  7: 'ALTER TABLE vie_prgr ADD COLUMN diavenc INTEGER;',
  8: 'ALTER TABLE vie_prgr ADD COLUMN pr1esto REAL;',
  9: 'ALTER TABLE vie_prgr ADD COLUMN forlinh INTEGER;',
  10: 'ALTER TABLE vie_prgr ADD COLUMN obsprod TEXT;',
  11: 'ALTER TABLE vie_prgr ADD COLUMN vitrine REAL;',
};
